#!/usr/bin/python3

import io
import sys
import subprocess
from datetime import datetime

def main():

  # check for correct number of arguments
  if len(sys.argv) != 4:
    print("Usage: taggen.py <ver> <str> <output>")
    sys.exit(1)

  # run git
  hash = subprocess.check_output(["git", "describe", "--always"]).decode("utf-8").replace("\n","")

  # system time
  time = datetime.today().strftime('%d%m%Y')

  # c header generation
  fp = open(sys.argv[3], "wt")
  fp.seek(io.SEEK_SET, 0)
  fp.write("// This file is automatically generated by script.\n\n")
  fp.write("#ifndef _BUILD_VERSION_H\n")
  fp.write("#define _BUILD_VERSION_H\n\n")
  fp.write(f"#define COMMIT_HASH \"{hash}\"\n")
  fp.write(f"#define BUILD_VERSION \"quikos {sys.argv[1]} {sys.argv[2]}_{time}\"\n\n")
  fp.write("#endif /* _BUILD_VERSION_H */\n")

if __name__ == "__main__":
  main()
